# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2020
  project: Bowserwerk Job system
  version: 1.1
  release: 1.1.0
  latex_documents:
  - - Index
    - bw_jobs.tex
    - Bowserwerk Job system
    - Vincent Bärtsch
    - manual
  html_theme_options:
    github_repository: browserwerk/bw-jobs
    github_branch: master
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - https://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - https://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
